In [92]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from pathlib import Path
from sklearn.metrics import confusion_matrix

In [93]:
train_df = pd.read_csv(Path('Resources/Generator/2019loans.csv'))
train_df.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0     7000.0    0.1894       256.38       MORTGAGE     75000.0   
1    40000.0    0.1614       975.71       MORTGAGE    102000.0   
2    11000.0    0.2055       294.81           RENT     45000.0   
3     4000.0    0.1612       140.87       MORTGAGE     38000.0   
4    14000.0    0.1797       505.93       MORTGAGE     43000.0   

  verification_status pymnt_plan    dti  delinq_2yrs  inq_last_6mths  ...  \
0        Not Verified          n  28.62          0.0             2.0  ...   
1     Source Verified          n  11.72          2.0             0.0  ...   
2            Verified          n  37.25          1.0             3.0  ...   
3        Not Verified          n  42.89          1.0             0.0  ...   
4     Source Verified          n  22.16          1.0             0.0  ...   

   percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0              87.5                   0.0        0.0         352260.0   
1               0.0                   0.0        0.0         294664.0   
2               7.7                   0.0        0.0          92228.0   
3             100.0                   0.0        0.0         284273.0   
4              25.0                   0.0        0.0         120280.0   

  total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  \
0           62666.0         35000.0                     10000.0   
1          109911.0          9000.0                     71044.0   
2           36007.0         33000.0                     46328.0   
3           52236.0         13500.0                     52017.0   
4           88147.0         33300.0                     78680.0   

   hardship_flag  debt_settlement_flag    target  
0              N                     N  low_risk  
1              N                     N  low_risk  
2              N                     N  low_risk  
3              N                     N  low_risk  
4              N                     N  low_risk  

[5 rows x 84 columns]

In [94]:
y_train = train_df["target"]
train_target_names=["low_risk", "high_risk"]

In [95]:
X_train= train_df.drop("target", axis=1)
X_train.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0     7000.0    0.1894       256.38       MORTGAGE     75000.0   
1    40000.0    0.1614       975.71       MORTGAGE    102000.0   
2    11000.0    0.2055       294.81           RENT     45000.0   
3     4000.0    0.1612       140.87       MORTGAGE     38000.0   
4    14000.0    0.1797       505.93       MORTGAGE     43000.0   

  verification_status pymnt_plan    dti  delinq_2yrs  inq_last_6mths  ...  \
0        Not Verified          n  28.62          0.0             2.0  ...   
1     Source Verified          n  11.72          2.0             0.0  ...   
2            Verified          n  37.25          1.0             3.0  ...   
3        Not Verified          n  42.89          1.0             0.0  ...   
4     Source Verified          n  22.16          1.0             0.0  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0           100.0              87.5                   0.0        0.0   
1            85.7               0.0                   0.0        0.0   
2            94.3               7.7                   0.0        0.0   
3            92.9             100.0                   0.0        0.0   
4            84.1              25.0                   0.0        0.0   

  tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
0        352260.0            62666.0         35000.0   
1        294664.0           109911.0          9000.0   
2         92228.0            36007.0         33000.0   
3        284273.0            52236.0         13500.0   
4        120280.0            88147.0         33300.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     10000.0              N                     N  
1                     71044.0              N                     N  
2                     46328.0              N                     N  
3                     52017.0              N                     N  
4                     78680.0              N                     N  

[5 rows x 83 columns]

In [96]:
train_dummy= pd.get_dummies(train_df)
print(train_dummy.columns)
train_dummy.head()

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_in

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0     7000.0    0.1894       256.38     75000.0  28.62          0.0   
1    40000.0    0.1614       975.71    102000.0  11.72          2.0   
2    11000.0    0.2055       294.81     45000.0  37.25          1.0   
3     4000.0    0.1612       140.87     38000.0  42.89          1.0   
4    14000.0    0.1797       505.93     43000.0  22.16          1.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  ...  initial_list_status_f  \
0             2.0      20.0      0.0    40414.0  ...                      1   
1             0.0      10.0      0.0    43531.0  ...                      0   
2             3.0      23.0      0.0     8242.0  ...                      0   
3             0.0       7.0      0.0    12767.0  ...                      0   
4             0.0      22.0      0.0    11182.0  ...                      0   

   initial_list_status_w  application_type_Individual  \
0                      0                            1   
1                      1                            1   
2                      1                            1   
3                      1                            0   
4                      1                            1   

   application_type_Joint App  hardship_flag_N  hardship_flag_Y  \
0                           0                1                0   
1                           0                1                0   
2                           0                1                0   
3                           1                1                0   
4                           0                1                0   

   debt_settlement_flag_N  debt_settlement_flag_Y  target_high_risk  \
0                       1                       0                 0   
1                       1                       0                 0   
2                       1                       0                 0   
3                       1                       0                 0   
4                       1                       0                 0   

   target_low_risk  
0                1  
1                1  
2                1  
3                1  
4                1  

[5 rows x 94 columns]

In [97]:
y_train_label = LabelEncoder().fit_transform(train_df['target'])
y_train_label

array([1, 1, 1, ..., 0, 0, 0])

In [98]:
test_df = pd.read_csv(Path('Resources/Generator/2020Q1loans.csv'))
test_df.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0    40000.0    0.1033       856.40           RENT    128700.0   
1    24450.0    0.1430       572.72       MORTGAGE     44574.0   
2    13500.0    0.1430       316.23            OWN     60000.0   
3    10625.0    0.1774       268.31           RENT     60000.0   
4     6375.0    0.1862       232.46           RENT     60000.0   

  verification_status pymnt_plan    dti  delinq_2yrs  inq_last_6mths  ...  \
0     Source Verified          n  12.47          0.0             1.0  ...   
1        Not Verified          n  15.05          0.0             1.0  ...   
2        Not Verified          n  28.72          0.0             0.0  ...   
3            Verified          n  15.70          0.0             4.0  ...   
4     Source Verified          n  35.50          0.0             0.0  ...   

   percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  tot_hi_cred_lim  \
0              57.1                   0.0        0.0          63915.0   
1               0.0                   0.0        0.0         136425.0   
2               0.0                   0.0        0.0          82124.0   
3              20.0                   0.0        0.0          54855.0   
4              75.0                   0.0        0.0          90445.0   

  total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  \
0           49510.0         49400.0                     14515.0   
1           19439.0         15500.0                     18925.0   
2           65000.0          5400.0                     61724.0   
3           50335.0         23200.0                     26255.0   
4           56541.0         15300.0                     72345.0   

   hardship_flag  debt_settlement_flag    target  
0              Y                     N  low_risk  
1              N                     N  low_risk  
2              Y                     N  low_risk  
3              N                     N  low_risk  
4              N                     N  low_risk  

[5 rows x 84 columns]

In [99]:
y_test = test_df["target"]
test_target_names=["low_risk", "high_risk"]

In [100]:
X_test= test_df.drop("target", axis=1)
X_test.head()

loan_amnt  int_rate  installment home_ownership  annual_inc  \
0    40000.0    0.1033       856.40           RENT    128700.0   
1    24450.0    0.1430       572.72       MORTGAGE     44574.0   
2    13500.0    0.1430       316.23            OWN     60000.0   
3    10625.0    0.1774       268.31           RENT     60000.0   
4     6375.0    0.1862       232.46           RENT     60000.0   

  verification_status pymnt_plan    dti  delinq_2yrs  inq_last_6mths  ...  \
0     Source Verified          n  12.47          0.0             1.0  ...   
1        Not Verified          n  15.05          0.0             1.0  ...   
2        Not Verified          n  28.72          0.0             0.0  ...   
3            Verified          n  15.70          0.0             4.0  ...   
4     Source Verified          n  35.50          0.0             0.0  ...   

   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \
0            84.2              57.1                   0.0        0.0   
1           100.0               0.0                   0.0        0.0   
2           100.0               0.0                   0.0        0.0   
3            91.4              20.0                   0.0        0.0   
4           100.0              75.0                   0.0        0.0   

  tot_hi_cred_lim  total_bal_ex_mort  total_bc_limit  \
0         63915.0            49510.0         49400.0   
1        136425.0            19439.0         15500.0   
2         82124.0            65000.0          5400.0   
3         54855.0            50335.0         23200.0   
4         90445.0            56541.0         15300.0   

   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  
0                     14515.0              Y                     N  
1                     18925.0              N                     N  
2                     61724.0              Y                     N  
3                     26255.0              N                     N  
4                     72345.0              N                     N  

[5 rows x 83 columns]

In [101]:
test_dummy= pd.get_dummies(test_df)
print(test_dummy.columns)
test_dummy.head()

Index(['loan_amnt', 'int_rate', 'installment', 'annual_inc', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'total_acc', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_in

loan_amnt  int_rate  installment  annual_inc    dti  delinq_2yrs  \
0    40000.0    0.1033       856.40    128700.0  12.47          0.0   
1    24450.0    0.1430       572.72     44574.0  15.05          0.0   
2    13500.0    0.1430       316.23     60000.0  28.72          0.0   
3    10625.0    0.1774       268.31     60000.0  15.70          0.0   
4     6375.0    0.1862       232.46     60000.0  35.50          0.0   

   inq_last_6mths  open_acc  pub_rec  revol_bal  ...  pymnt_plan_n  \
0             1.0       8.0      0.0    38113.0  ...             1   
1             1.0       6.0      0.0     1665.0  ...             1   
2             0.0       8.0      0.0    13857.0  ...             1   
3             4.0      17.0      0.0     6216.0  ...             1   
4             0.0      13.0      0.0    12681.0  ...             1   

   initial_list_status_f  initial_list_status_w  application_type_Individual  \
0                      0                      1                            1   
1                      0                      1                            1   
2                      0                      1                            1   
3                      0                      1                            1   
4                      0                      1                            1   

   application_type_Joint App  hardship_flag_N  hardship_flag_Y  \
0                           0                0                1   
1                           0                1                0   
2                           0                0                1   
3                           0                1                0   
4                           0                1                0   

   debt_settlement_flag_N  target_high_risk  target_low_risk  
0                       1                 0                1  
1                       1                 0                1  
2                       1                 0                1  
3                       1                 0                1  
4                       1                 0                1  

[5 rows x 93 columns]

In [102]:
y_test_label = LabelEncoder().fit_transform(test_df['target'])
y_test_label

array([1, 1, 1, ..., 0, 0, 0])

In [103]:
# Convert categorical data to numeric and separate target feature for training data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_dummy, y_train_label, random_state=100)

In [104]:
# Convert categorical data to numeric and separate target feature for testing data
X_train, X_test, y_train, y_test = train_test_split(test_dummy, y_test_label, random_state=100)

In [105]:
# add missing dummy variables to testing set

In [106]:
# Train the Logistic Regression model on the unscaled data and print the model score
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.81310266591038
Testing Data Score: 0.8222789115646258


/Users/laurakemp/opt/anaconda3/envs/PythonData/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [107]:
# Train a Random Forest Classifier model and print the model score
y_true = y_test
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_true, y_pred)
cm

array([[430, 157],
       [ 52, 537]])

In [108]:
# Scale the data
from sklearn.preprocessing import StandardScaler
data_scaler_train = StandardScaler().fit(X_train)
X_train_scaled = data_scaler_train.transform(X_train)
X_train_scaled
data_scaler_test = StandardScaler().fit(X_train)
X_test_scaled = data_scaler_test.transform(X_train)
X_test_scaled


array([[-1.04996242,  0.66260965, -0.92653475, ...,  0.        ,
        -1.00056738,  1.00056738],
       [ 1.18870369, -1.14201293,  1.37351356, ...,  0.        ,
         0.99943295, -0.99943295],
       [-0.89164791,  0.07779428, -0.77426887, ...,  0.        ,
         0.99943295, -0.99943295],
       ...,
       [-1.16127731, -1.25101697, -1.16032082, ...,  0.        ,
        -1.00056738,  1.00056738],
       [-0.44391469, -1.25101697, -0.39553544, ...,  0.        ,
        -1.00056738,  1.00056738],
       [ 1.44349111, -0.29593389,  0.72443535, ...,  0.        ,
         0.99943295, -0.99943295]])

In [109]:
# Train the Logistic Regression model on the scaled data and print the model score
print(f"Training Data Score: {classifier.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test_scaled, y_test)}")

Training Data Score: 0.8318207600680658


ValueError: Found input variables with inconsistent numbers of samples: [1176, 3526]

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score